# Generated by Django 5.2.1 on 2025-05-12 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                (
                    'telefone',
                    models.CharField(
                        blank=True,
                        help_text='Use o formato: (99) 99999-9999',
                        max_length=15,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Telefone deve ter o formato: (99) 99999-9999 ou (99) 9999-9999',
                                regex='^\\(?\\d{2}\\)?\\s?\\s{4,5}-?\\d{4}$',
                            )
                        ],
                    ),
                ),
                ('codinome', models.CharField(max_length=255, unique=True)),
                (
                    'grupo',
                    models.CharField(
                        choices=[
                            ('LJ', 'Liga da Justiça'),
                            ('V', 'Vingadores'),
                        ],
                        default='LJ',
                        help_text='Escolha seu grupo',
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
