# Generated by Django 5.2.1 on 2025-05-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='codinome',
            field=models.CharField(max_length=255),
        ),
    ]
