# Generated by Django 5.2.1 on 2025-05-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(
                blank=True,
                help_text='Use o formato: (99) 99999-9999',
                max_length=15,
                null=True,
            ),
        ),
    ]
