# Generated by Django 5.2.1 on 2025-05-19 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(
                blank=True,
                help_text='Use o formato: (99) 99999-9999',
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}\\-?\\d{4}$'
                    )
                ],
            ),
        ),
    ]
